name: Frontend CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install yarn
      run: apt install yarn
    - name: Run unit tests
      run: yarn test:unit
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install yarn
      run: apt install yarn
    - name: Run unit tests
      run: yarn lint
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the frontend Docker image
      run: docker build ./frontend --file frontend/Dockerfile --tag frontend
   
